// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleCSharpEnv using AI Type  and AI Model 

ROOST_METHOD_HASH=Run_a2e9436d0a
ROOST_METHOD_SIG_HASH=Run_9ce955ed80

   ########## Test-Scenarios ##########  

Based on the provided method and related code, here are several test scenarios for the `Run` method of the `DepthFirstSearch` class:

Scenario 1: Null Graph Handling

Details:
  TestName: ThrowArgumentNullExceptionWhenGraphIsNull
  Description: Verify that the method throws an ArgumentNullException when a null graph is passed.
Execution:
  Arrange: Create a DepthFirstSearch instance with no graph.
  Act: Call the Run method with a null graph.
  Assert: Expect an ArgumentNullException to be thrown.
Validation:
  This test ensures that the method properly handles null input, preventing null reference exceptions later in the execution.

Scenario 2: Empty Graph Processing

Details:
  TestName: ProcessEmptyGraphWithoutException
  Description: Ensure the method can handle an empty graph without throwing exceptions.
Execution:
  Arrange: Create a DepthFirstSearch instance and an empty IGraph<DFSVertex>.
  Act: Call the Run method with the empty graph.
  Assert: Verify that no exception is thrown and the method completes successfully.
Validation:
  This test confirms that the method can handle edge cases like empty graphs gracefully.

Scenario 3: Single Vertex Graph Processing

Details:
  TestName: ProcessSingleVertexGraphCorrectly
  Description: Verify that a graph with a single vertex is processed correctly.
Execution:
  Arrange: Create a DepthFirstSearch instance and an IGraph<DFSVertex> with one vertex.
  Act: Call the Run method with the single-vertex graph.
  Assert: Check that the vertex's StartTime and EndTime are set and Processed is true.
Validation:
  This test ensures that the basic functionality works for the simplest possible graph.

Scenario 4: Multiple Disconnected Vertices Processing

Details:
  TestName: ProcessMultipleDisconnectedVerticesCorrectly
  Description: Ensure that a graph with multiple disconnected vertices is processed correctly.
Execution:
  Arrange: Create a DepthFirstSearch instance and an IGraph<DFSVertex> with multiple disconnected vertices.
  Act: Call the Run method with the graph.
  Assert: Verify that all vertices have been processed (Processed is true, StartTime and EndTime are set).
Validation:
  This test checks if the method correctly handles graphs with no edges, processing all vertices independently.

Scenario 5: Connected Graph Processing

Details:
  TestName: ProcessConnectedGraphCorrectly
  Description: Verify that a connected graph is processed in the correct depth-first order.
Execution:
  Arrange: Create a DepthFirstSearch instance and an IGraph<DFSVertex> with connected vertices.
  Act: Call the Run method with the connected graph.
  Assert: Check that all vertices are processed and that the StartTime and EndTime values reflect a valid depth-first traversal order.
Validation:
  This test ensures that the core functionality of depth-first search works correctly on a typical connected graph.

Scenario 6: Cyclic Graph Processing

Details:
  TestName: ProcessCyclicGraphWithoutInfiniteLoop
  Description: Ensure that a graph containing cycles is processed without getting stuck in an infinite loop.
Execution:
  Arrange: Create a DepthFirstSearch instance and an IGraph<DFSVertex> with cycles.
  Act: Call the Run method with the cyclic graph.
  Assert: Verify that all vertices are processed and the method terminates.
Validation:
  This test checks if the method can handle graphs with cycles, which is crucial for preventing infinite recursion.

Scenario 7: Large Graph Performance

Details:
  TestName: ProcessLargeGraphWithinReasonableTime
  Description: Verify that the method can process a large graph within a reasonable time frame.
Execution:
  Arrange: Create a DepthFirstSearch instance and a large IGraph<DFSVertex> (e.g., 10000 vertices).
  Act: Call the Run method with the large graph and measure execution time.
  Assert: Check that all vertices are processed and the execution time is within an acceptable limit.
Validation:
  This test ensures that the method's performance scales well with larger graphs.

Scenario 8: Preservation of Graph Structure

Details:
  TestName: PreserveGraphStructureAfterProcessing
  Description: Ensure that the original graph structure remains unchanged after processing.
Execution:
  Arrange: Create a DepthFirstSearch instance and an IGraph<DFSVertex>. Store the initial structure.
  Act: Call the Run method with the graph.
  Assert: Verify that the graph's structure (vertices and edges) is the same as before processing.
Validation:
  This test checks that the DFS algorithm doesn't modify the underlying graph structure, which is important for maintaining data integrity.

These test scenarios cover various aspects of the `Run` method, including edge cases, error handling, and core functionality. They should provide a comprehensive suite for validating the DepthFirstSearch implementation.


*/

// ********RoostGPT********
using NUnit.Framework;
using LunarDoggo.Datastructures.Graphs;
using LunarDoggo.Algorithms.Graphs.Pathfinding;
using System;
using System.Linq;

namespace LunarDoggo.Algorithms.Graphs.Pathfinding.Test
{
    [TestFixture]
    public class Run628Test
    {
        private DepthFirstSearch dfs;

        [SetUp]
        public void Setup()
        {
            dfs = new DepthFirstSearch();
        }

        [Test, Category("invalid")]
        public void ThrowArgumentNullExceptionWhenGraphIsNull()
        {
            Assert.Throws<ArgumentNullException>(() => dfs.Run(null));
        }

        [Test, Category("valid")]
        public void ProcessEmptyGraphWithoutException()
        {
            var graph = new UndirectedUnweightedGraph<DFSVertex>();
            Assert.DoesNotThrow(() => dfs.Run(graph));
        }

        [Test, Category("valid")]
        public void ProcessSingleVertexGraphCorrectly()
        {
            var graph = new UndirectedUnweightedGraph<DFSVertex>();
            var vertex = graph.AddVertex(new DFSVertex());

            dfs.Run(graph);

            Assert.That(vertex.Value.Processed, Is.True);
            Assert.That(vertex.Value.StartTime, Is.GreaterThanOrEqualTo(0));
            Assert.That(vertex.Value.EndTime, Is.GreaterThan(vertex.Value.StartTime));
        }

        [Test, Category("valid")]
        public void ProcessMultipleDisconnectedVerticesCorrectly()
        {
            var graph = new UndirectedUnweightedGraph<DFSVertex>();
            var vertex1 = graph.AddVertex(new DFSVertex());
            var vertex2 = graph.AddVertex(new DFSVertex());
            var vertex3 = graph.AddVertex(new DFSVertex());

            dfs.Run(graph);

            Assert.That(graph.Vertices.All(v => v.Value.Processed), Is.True);
            Assert.That(graph.Vertices.All(v => v.Value.StartTime >= 0), Is.True);
            Assert.That(graph.Vertices.All(v => v.Value.EndTime > v.Value.StartTime), Is.True);
        }

        [Test, Category("valid")]
        public void ProcessConnectedGraphCorrectly()
        {
            var graph = new UndirectedUnweightedGraph<DFSVertex>();
            var vertex1 = graph.AddVertex(new DFSVertex());
            var vertex2 = graph.AddVertex(new DFSVertex());
            var vertex3 = graph.AddVertex(new DFSVertex());
            graph.AddEdge(vertex1, vertex2);
            graph.AddEdge(vertex2, vertex3);

            dfs.Run(graph);

            Assert.That(graph.Vertices.All(v => v.Value.Processed), Is.True);
            Assert.That(graph.Vertices.All(v => v.Value.StartTime >= 0), Is.True);
            Assert.That(graph.Vertices.All(v => v.Value.EndTime > v.Value.StartTime), Is.True);
            Assert.That(vertex1.Value.StartTime < vertex2.Value.StartTime);
            Assert.That(vertex2.Value.StartTime < vertex3.Value.StartTime);
            Assert.That(vertex3.Value.EndTime < vertex2.Value.EndTime);
            Assert.That(vertex2.Value.EndTime < vertex1.Value.EndTime);
        }

        [Test, Category("valid")]
        public void ProcessCyclicGraphWithoutInfiniteLoop()
        {
            var graph = new UndirectedUnweightedGraph<DFSVertex>();
            var vertex1 = graph.AddVertex(new DFSVertex());
            var vertex2 = graph.AddVertex(new DFSVertex());
            var vertex3 = graph.AddVertex(new DFSVertex());
            graph.AddEdge(vertex1, vertex2);
            graph.AddEdge(vertex2, vertex3);
            graph.AddEdge(vertex3, vertex1);

            dfs.Run(graph);

            Assert.That(graph.Vertices.All(v => v.Value.Processed), Is.True);
            Assert.That(graph.Vertices.All(v => v.Value.StartTime >= 0), Is.True);
            Assert.That(graph.Vertices.All(v => v.Value.EndTime > v.Value.StartTime), Is.True);
        }

        [Test, Category("valid")]
        public void ProcessLargeGraphWithinReasonableTime()
        {
            var graph = new UndirectedUnweightedGraph<DFSVertex>();
            for (int i = 0; i < 10000; i++)
            {
                graph.AddVertex(new DFSVertex());
            }

            var startTime = DateTime.Now;
            dfs.Run(graph);
            var endTime = DateTime.Now;

            Assert.That(graph.Vertices.All(v => v.Value.Processed), Is.True);
            Assert.That((endTime - startTime).TotalSeconds, Is.LessThan(5)); // Adjust the time limit as needed
        }

        [Test, Category("valid")]
        public void PreserveGraphStructureAfterProcessing()
        {
            var graph = new UndirectedUnweightedGraph<DFSVertex>();
            var vertex1 = graph.AddVertex(new DFSVertex());
            var vertex2 = graph.AddVertex(new DFSVertex());
            var vertex3 = graph.AddVertex(new DFSVertex());
            graph.AddEdge(vertex1, vertex2);
            graph.AddEdge(vertex2, vertex3);

            var initialVertexCount = graph.Vertices.Count();
            var initialEdgeCount = graph.Edges.Count();

            dfs.Run(graph);

            Assert.That(graph.Vertices.Count(), Is.EqualTo(initialVertexCount));
            Assert.That(graph.Edges.Count(), Is.EqualTo(initialEdgeCount));
            Assert.That(vertex1.Adjacent.Contains(vertex2), Is.True);
            Assert.That(vertex2.Adjacent.Contains(vertex3), Is.True);
        }
    }
}
